config/routes.rb
Rails.application.routes.draw do
  root 'miniblogs#index'
  resources:miniblogs do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/miniblog.rb
class Miniblog < ApplicationRecord
    validates :content,length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/miniblogs_controller.rb
class MiniblogsController < ApplicationController
  before_action :set_miniblog,only: [:edit, :update,:destroy]

  def index
    @miniblogs=Miniblog.all
  end

  def new
    if params[:back]
      @miniblog=Miniblog.new(miniblog_params)
    else
      @miniblog=Miniblog.new
    end
  end

  def create
    @miniblog=Miniblog.new(miniblog_params)
      if @miniblog.save
        redirect_to miniblogs_path,notice:"ミニブログを作成しました！"
      else
        render'new'
      end
    end

  def edit
  end

  def update
  if @miniblog.update(miniblog_params)
    redirect_to miniblogs_path, notice: "ミニブログを編集しました！"
    else
    render 'edit'
    end
  end

  def destroy
    @miniblog.destroy
    redirect_to miniblogs_path, notice:"ミニブログを削除しました！"
  end

  def confirm
    @miniblog=Miniblog.new(miniblog_params)
    render :new if @miniblog.invalid?
  end

  private

  def miniblog_params
    params.require(:miniblog).permit(:content)
  end

  def set_miniblog
    @miniblog=Miniblog.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/miniblogs_helper.rb
module MiniblogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_miniblogs_path
    elsif action_name == 'edit'
      miniblog_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railswork</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header>
  </header>

  <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">ミニブログ</a>
        </div>
        <div class="collapse navbar-collapse" id="navigation">
          <p class="navbar-text navbar-right">テストユーザ さんでログイン中</p>
        </div>
      </div>
  </nav>



    <%= yield %>

  <footer>
    <p>運営会社hogehoge,Inc.</p>
    <p>© 2015-2019 hogehoge,Inc.</p>
  </footer>

  </body>
</html>

app/views/miniblogs/_form.html.erb
<%= form_with(model: @miniblog, local: true,url:choose_new_or_edit) do |form| %>


  <% if @miniblog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @miniblog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @miniblog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to 'ミニブログ一覧画面へ移動する', miniblogs_path %>

app/views/miniblogs/confirm.html.erb
<h3>以下の内容で、投稿します。よろしいですか？</h3>


<%= form_with(model: @miniblog, url: miniblogs_path, local: true) do |form| %>
  <%= form.hidden_field :content %>


  <p>本文:<%= @miniblog.content %></p>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @miniblog, url: new_miniblog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る" ,name: 'back'%>
<% end %>

app/views/miniblogs/edit.html.erb
  <h2>ミニブログを編集する</h2>

  <%= render 'form' %>

app/views/miniblogs/index.html.erb
<h1>ミニブログ一覧</h1>

<p><%= notice %></p>

<table class="table">

<% @miniblogs.each do |blog| %>
  <tr>
    <td><%= blog.content %></td>
    <td><%=link_to"ミニブログを編集する",edit_miniblog_path(blog.id)%></td>
    <td><%= link_to 'ミニブログを削除する', miniblog_path(blog.id), method: :delete,data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</table>

<%= link_to '新しくミニブログを投稿する', new_miniblog_path %>

app/views/miniblogs/new.html.erb
  <h2>ミニブログを作成する</h2>

  <%= render 'form' %>